### ISSUE TITLE
Terraform Provider Development Program - Review

### ISSUE THREAD

**Issue by cgriggs01** [OpenNebula/addon-terraform#12]
I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the develop branch at git commit `2928c36`

- [ ] The name of this repository should be `terraform-provider-opennebula/`. 

- [ ] A makefile should be added  and named GNUmakefile which is standard across all Terraform providers, feel free to copy the [NULL provider makefile](https://github.com/terraform-providers/terraform-provider-tls/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=opennebula

- [ ] Along with the makefile there are four bash scripts kept in a `scripts/` directory that are used in different processes of testing and release, these can all be copied from the [NULL provider](https://github.com/terraform-providers/terraform-provider-null/tree/master/scripts) 

- [ ] All Terraform providers have now switched to using Go modules for managing and vendoring dependancies for the provider but in addition to that, we ask that you check-in all the required dependancies into a `vendor/` directory. This is so that our nightly testing environment does ping GitHub for ever dependancies in all 100+ TF providers. 

- [ ] If a resource cannot be found(404) in the READ function, we should do a d.SetId("") to remove it from the statefile. You also wouldn't need to return an error then. Terraform will just treat it as a resource that never existed and try and create it.

- [ ] Attributes should be read and set on Read so that differences between the configuration and the actual state can be caught. Any non-scalar values (TypeList, TypeSet, TypeMap) should have errors checked when setting. The reasoning for this is that the provider should never `panic`.

- [ ] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. 

- [ ] You will need to build website documentation in a website/ directory that will be hosted on [Terraform.io](Terraform.io/docs/providers/index.html) for each resource and data source, these are all written in Markdown with a ruby layout file for the sidebar formatting.  Check out the [Github provider](https://github.com/terraform-providers/terraform-provider-github) website docs as a good example. 

- [ ] There is a standard README.md for of the official provider, see [Null provider README.md](https://github.com/terraform-providers/terraform-provider-null/blob/master/README.md)

Let me know if you have any questions.

**Comment by tinova** [comment]
Repo name changed to **terraform-provider-opennebula**

**Comment by jaypif** [comment]
Hi @cgriggs01 ,

In PR #18 we fixed all points you raised (1 commit per point). Can you take a look at this PR and let us know here ?
If you have any comments please write them in review mode (or in the PR directly). 
I prefer merging in master the correct PR.

Thank you

**Comment by cgriggs01** [comment]
Hey Team,

Changes are looking great! I was able to get the acceptance test running but am hitting a few failed tests, do you have any thoughts on why these tests are failing? --> [test.txt](https://github.com/OpenNebula/terraform-provider-opennebula/files/3838977/test.txt)

Thanks for your help!

**Comment by jaypif** [comment]
Hi @cgriggs01 

I don't know how you bot works but it seems that your failures are linked with HTTP request.
We added travis CI to run tests on this repo and it starts a docker to execute request on another instance. 

I will try with the specific account on the external service dedicated to your tests.

**Comment by jaypif** [comment]
Hi @cgriggs01 

Can you retry with your bot. The issue you add was because the testing lab was not running. I tried on my side now and it seems OK.

**Comment by cgriggs01** [comment]
Hey @jaypif 

I'm still getting the same output for the tests. I have pulled from "master" branch this time.

**Comment by jaypif** [comment]
HI @cgriggs01 

what is the value of the variable "endpoint" in the configuration of your bot ?
I think it is link to this issue: https://nanxiao.me/en/fix-unsupported-protocol-scheme-issue-in-golang/.

Can you configure the variable `endpoint` with `http://72.14.177.117:2633/RPC2` ?

Regards

**Comment by cgriggs01** [comment]
I was just using the `72.14.177.117` for the `endpoint` variable. 

Retesting now.

**Comment by cgriggs01** [comment]
Everything checks out so far. Im going to do one final check and then we can begin the migration a release process. Are you ready for the provider to be released? 

I'll be moving this code base over to the `github.com/terraform-providers/` organization. Whom from your team will need `write` access for the provider. 

Once the provider has been moved over, we'll kick off the first release under version `0.1.0`. As well the OpenNebula provider documentation will be pushed to Terraform.io from a `stable-website` branch of the repo.

**Comment by jaypif** [comment]
Hi @cgriggs01 

Great news! Thank you for your time.

Here is the list of people who should be able to write on the repo:
@tinova @christian7007 @jaypif @treywelsh @hekmon @aloababa 

Thanks

**Comment by jaypif** [comment]
Hi @cgriggs01 

Do you have any idea when you plan to move the code base to `terraform-providers`' github ? 

It is just to prepare some blog posts and social networks posts :).

Thanks

**Comment by cgriggs01** [comment]
Hey @jaypif, 

I hit a few issues on my side but am unblocked now. I just attempted the first binary release but unfortunately the provider did not build and compile for `386` architecture. You should have explicitly declared things as `uint64` , not just `uint` here --> [acl.go#L49-L68](https://github.com/OpenNebula/one/blob/38bb3947207f8ec082b480d8b1c889e153781559/src/oca/go/src/goca/schemas/acl/acl.go#L49-L68)

Appologies for this last minute item, but would you be able to address this?

**Comment by jaypif** [comment]
Hi @cgriggs01 ,

The issue you faced when you tried to compile for `386` architecture was linked to an issue in a dependency.
We fixed it in the dependency and the provider code has also been updated to use last version of Goca.

Thanks to this we will be able to link the v0.1.0 of the provider to 5.10 version of OpenNebula. It will ease a lot the versioning of the provider.

Can you retry and let us now ?

Thanks

**Comment by cgriggs01** [comment]
Hey @jaypif,

I was able to get the provider to build an release to [releases.hashicorp.com](https://releases.hashicorp.com/terraform-provider-opennebula/0.1.0/) and the documentation has been posted to [terraform.io](https://www.terraform.io/docs/providers/opennebula/index.html).  Thanks for your help and congratulations on completing the program. 

I've sent our community guideline and etiquette to @jaypif and @tinova can will need email address for @christian7007 @treywelsh @hekmon @aloababa as well so they can be onboarded.

**Comment by christian7007** [comment]
Hello @cgriggs01 here you have my email: `cgonzalez@opennebula.systems`

**Comment by jaypif** [comment]
Hi Chris,

Here are all the emails:

   - @christian7007 <https://github.com/christian7007>:
   cgonzalez@opennebula.systems
   - @treywelsh <https://github.com/treywelsh>: treywelsh2@gmail.com
   - @hekmon <https://github.com/hekmon>: edouardhur@gmail.com
   - @aloababa <https://github.com/aloababa>: gustin.ben@gmail.com

I already read some rules I will take a look to other ones and let you know

Thanks for the update about the doc :)

Regards


Jean-Philippe FOURES

Port. : 06 89 01 09 42
Mail : jean.philippe.foures@gmail.com


Le mar. 26 nov. 2019 à 01:31, Chris Griggs <notifications@github.com> a
écrit :

**Comment by jaypif** [comment]
Hi @cgriggs01 

I want to thank you for your help for getting this provider official.

We are very proud of this and very excited about this.

Thank you


PS: Can we close this is issue. I want to ask people to open issues and PR directly ion the official repo now ;).
